# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "ListingsAll"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    filterCollection:
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  filterCollection:
    type: select
    options:
      allow_empty: false
      values: data.listings.filtering[*]
      value_key: id
      text_key: filterCollectionName
